### ISSUE TITLE
Wrong code when I install with npm

### ISSUE THREAD

**Issue by damaca** [tracker1/node-uuid4#1]
Hi,

I installed this library with "npm install uuid4" and uuid.valid didn't work. Taking a look into the code I saw the code is not the same than the master branch here. For example:

exports = module.exports = generateUuid;
exports.async = generateUuidAsync;
exports.sync = generateUuidSync;
exports.valid = generateUuid;

**Comment by yat1ma30** [comment]
:+1:

**Comment by tracker1** [comment]
Not sure how I missed this notification... (I'm following a lot of repos), will try to get this corrected first thing tomorrow morning).

**Comment by jinscript** [comment]
Hey any updates on this one?
Can you try bumping the version and see if it helps?

**Comment by tracker1** [comment]
should work now.

**Comment by tracker1** [comment]
1.1.1
