### ISSUE TITLE
browserifying this module brings in the entire half-magabyte browserify-crypto library with it

### ISSUE THREAD

**Issue by lxe** [tracker1/node-uuid4#3]
Using this module using browserify in the context of a browser causes browserify to add the entire browserify-crypto library to the bundle, (to replace node's native crypto library).

Be wary.

**Comment by tracker1** [comment]
You're browserifying your modules to run in node?  Or are you targeting the browser?

**Comment by tracker1** [comment]
added `browser.js` with entry in package.js that should work now...
