### ISSUE TITLE
valid function wrong export

### ISSUE THREAD

**Issue by igormaffei** [tracker1/node-uuid4#6]
Hi,
I've encountered an error in exporting the valid function.

Was this way:
exports.valid = generateUuid;

But correct is:
exports.valid = isUUID;

Could you change this?

Sorry, my English is not very good.

Thank you in advance.

**Comment by edo386** [comment]
The repository has the correct export, but for some reason installing via npm install loads an old version, use the following workaround:
package.json

```
"dependencies":{
 "uuid4": "https://github.com/tracker1/node-uuid4/tarball/master"
}
```

Related to: #1

**Comment by igormaffei** [comment]
Thank you.

**Comment by tracker1** [comment]
1.1.0 should be correct now... sorry
