### ISSUE TITLE
Returning a single string instead of a uuid-generating function?

### ISSUE THREAD

**Issue by jvmatl** [tracker1/node-uuid4#7]
This https://github.com/tracker1/node-uuid4/blob/03b0ae0a1212a7c5290da6bbd24642f94a33a419/browser.js#L54 looks like a bug: shouldn't this just be 
```  return genUUID;```
instead of 
``` return genUUID();```

??

**Comment by tracker1** [comment]
sorry, messed up the AMD support... should be fixed in v1.1.4

**Comment by jvmatl** [comment]
Thanks!
